# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/5.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    email:
        enabled: true
        sender_email: Oussema.hmaied1@esprit.tn
        sender_name: Oussema  # Optional