vich_uploader:
    db_driver: orm

    mappings:
        actualite_images:
            uri_prefix:         /images/actualite
            upload_destination: '%kernel.project_dir%/public/images/actualite'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true